# version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.prod.env

    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db.prod.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hello_django -d hello_django_prod"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      # - 1337:80
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: